// @remove-on-eject-begin
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */
// @remove-on-eject-end
'use strict';

// Do this as the first thing so that any code reading it knows the right env.
process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';

// Makes the script crash on unhandled rejections instead of silently
// ignoring them. In the future, promise rejections that are not handled will
// terminate the Node.js process with a non-zero exit code.
process.on('unhandledRejection', err => {
  throw err;
});

// Ensure environment variables are read.
require('../config/env');

const fs = require('fs');
const chalk = require('chalk');
const webpack = require('webpack');
const WebpackDevServer = require('webpack-dev-server');
const chokidar = require('chokidar');
const clearConsole = require('react-dev-utils/clearConsole');
const {
  choosePort,
  createCompiler,
  prepareProxy,
  prepareUrls,
} = require('react-dev-utils/WebpackDevServerUtils');
const paths = require('../config/paths');
const makeDevConfig = require('../config/webpack.config.dev');
const createDevServerConfig = require('../config/webpackDevServer.config');
const { setupBuild, processPublicFolder } = require('../lib/setup');

const useYarn = fs.existsSync(paths.yarnLockFile);
const isInteractive = process.stdout.isTTY;

// Tools like Cloud9 rely on this.
const DEFAULT_PORT = parseInt(process.env.PORT, 10) || 3000;
const HOST = process.env.HOST || '0.0.0.0';

// We attempt to use the default port but if it is busy, we offer the user to
// run on a different port. `detect()` Promise resolves to the next free port.
choosePort(HOST, DEFAULT_PORT)
  .then(port => {
    if (port == null) {
      // We have not found a port.
      return;
    }
    const protocol = process.env.HTTPS === 'true' ? 'https' : 'http';
    const appName = require(paths.appPackageJson).name;
    const urls = prepareUrls(protocol, HOST, port);
    // Create a webpack compiler that is configured with custom messages.
    const config = makeDevConfig(setupBuild(paths), urls.localUrlForBrowser);
    const compiler = createCompiler(webpack, config, appName, urls, useYarn);
    // Instructions printed by CRA are not relevant, so we replace them on success.
    patchInstructions(compiler);
    // Load proxy config
    const proxySetting = require(paths.appPackageJson).proxy;
    const proxyConfig = prepareProxy(proxySetting, paths.appPublic);
    // Serve webpack assets generated by the compiler over a web sever.
    const serverConfig = createDevServerConfig(
      proxyConfig,
      urls.lanUrlForConfig,
      config.output.publicPath
    );
    const devServer = new WebpackDevServer(compiler, serverConfig);
    // Launch WebpackDevServer.
    devServer.listen(port, HOST, err => {
      if (err) {
        return console.log(err);
      }
      if (isInteractive) {
        clearConsole();
      }
      console.log(chalk.cyan('Starting the development server...\n'));
      //openBrowser(urls.localUrlForBrowser);
    });

    // Also watch and copy the public directory.
    const appPublicWatch = chokidar
      .watch(paths.appPublic, {
        ignoreInitial: true,
      })
      .on('all', () => {
        console.log('Copying public folder...');
        processPublicFolder(paths);
        console.log('Done.');
      });

    ['SIGINT', 'SIGTERM'].forEach(function(sig) {
      process.on(sig, function() {
        devServer.close();
        appPublicWatch.close();
        process.exit();
      });
    });
  })
  .catch(err => {
    if (err && err.message) {
      console.log(err.message);
    }
    process.exit(1);
  });

const patchInstructions = compiler => {
  let isFirstCompile = true;
  compiler.plugin('done', stats => {
    const isSuccessful = !stats.hasErrors() && !stats.hasWarnings();
    if (isSuccessful && (isInteractive || isFirstCompile)) {
      clearConsole();
      console.log(chalk.green('Compiled successfully!'));
      printInstructions();
    }
    isFirstCompile = false;
  });
};

const printInstructions = () => {
  console.log();
  console.log(
    chalk.green(
      `You can now load the ${chalk.bold(
        'build'
      )} directory as a temporary extension in your browser.`
    )
  );
  console.log();
  console.log('Note that the development build is not optimized.');
  console.log(
    `To create a production build, use ` +
      `${chalk.cyan(`${useYarn ? 'yarn' : 'npm run'} build`)}.`
  );
  console.log();
};
